---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argoproj-metrics-poc-apiserver
  namespace: default
  labels:
    api: argoproj-metrics-poc
    apiserver: "true"
spec:
  selector:
    matchLabels:
      api: argoproj-metrics-poc
      apiserver: "true"
  replicas: 1
  template:
    metadata:
      labels:
        api: argoproj-metrics-poc
        apiserver: "true"
    spec:
      containers:
      - name: apiserver
        image: zachaller/argoproj-metrics-poc
        volumeMounts:
        - name: apiserver-certs
          mountPath: /apiserver.local.config/certificates
          readOnly: true
        command:
        - "./apiserver"
        args:
        - "--etcd-servers=http://etcd-svc:2379"
        - "--tls-cert-file=/apiserver.local.config/certificates/tls.crt"
        - "--tls-private-key-file=/apiserver.local.config/certificates/tls.key"
        - "--audit-log-path=-"
        - "--feature-gates=APIPriorityAndFairness=false"
        - "--audit-log-maxage=0"
        - "--audit-log-maxbackup=0"
        resources:
          requests:
            cpu: 100m
            memory: 20Mi
          limits:
            cpu: 100m
            memory: 512Mi
      volumes:
      - name: apiserver-certs
        secret:
          secretName: argoproj-metrics-poc
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: argoproj-metrics-poc
  namespace: default
  labels:
    api: argoproj-metrics-poc
    apiserver: "true"
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURzekNDQXB1Z0F3SUJBZ0lJU1BxaDJHTTlidTR3RFFZSktvWklodmNOQVFFTEJRQXdkREVMTUFrR0ExVUUKQmhNQ2RXNHhDekFKQmdOVkJBZ01Bbk4wTVFvd0NBWURWUVFIREFGc01Rb3dDQVlEVlFRS0RBRnZNUXN3Q1FZRApWUVFMREFKdmRURXpNREVHQTFVRUF3d3FZWEpuYjNCeWIyb3RiV1YwY21samN5MXdiMk10WTJWeWRHbG1hV05oCmRHVXRZWFYwYUc5eWFYUjVNQjRYRFRJeU1URXhOakF6TURFME9Wb1hEVE15TVRFeE16QXpNREUxTUZvd0t6RXAKTUNjR0ExVUVBeE1nWVhKbmIzQnliMm90YldWMGNtbGpjeTF3YjJNdVpHVm1ZWFZzZEM1emRtTXdnZ0VpTUEwRwpDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQzlyR3FnS1hkWHEzSXBabDBpQ1pEVDJ0L2ZhaG5DCmFha1Q3UGZNdFMyWjNrTWtYMlRmREY2NmgyTHpxOXFWRFY3YnJQSU5FL3BVbnBTNGZhSjhwNEVLSk5GNm9IMkcKQ1g1ZUo0WFl4MjhCdTRzeGxIb3QxSFl6NlU4ZHZ0eFFtd3FiY0Uyb2k3blduUGJNR3RNUHFKY0NWdkNYc3JnRwpNQ2pWaUxZOTJYVys1MitxQSs4bW04VjFTOStGSFFHTWNtVytDSXBQZUJ5TE9XVGkwUXhPTDRXY0FSeHk2QTlDCjBHQ2RGc0wraDBOblZyRWVobmpjcks0KzkxUUhqbWhCVVFUQmZmaVVkbWpWRkxDOVNFU0ExUlUzS1FsWnlrK1UKQWl0N2lDR0dRb2RTZE0rQ0JyOXp3RnF6QjN3Q3VJN1VUYk5rTUpPTFNlSEtqYVlacSs4ZmN2RDFBZ01CQUFHagpnWkV3Z1k0d0RnWURWUjBQQVFIL0JBUURBZ1dnTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGCkJRY0RBakFmQmdOVkhTTUVHREFXZ0JUSFZFTll3M241bUhyNndJcnNzMVRRcXQxbG9EQThCZ05WSFJFRU5UQXoKZ2dsc2IyTmhiR2h2YzNTQ0lHRnlaMjl3Y205cUxXMWxkSEpwWTNNdGNHOWpMbVJsWm1GMWJIUXVjM1pqaHdSLwpBQUFCTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFDYnlJd1dxRGU1Nnl6TGNBNjU2U3pCcHZDMmNiTTVESUhGCjBNTGpvMUVkU1dFTVFDNHlXa3pLbmJPNU45SGZoU0FaOGJ6SFpUL0lGaW9FR1U0d1g0SXJ5NlR4TkVuRnhPQ2QKMkdZTTlvU3VpYTFWdTA1aEVRdkF2RnFwWVc2bzhDSHFrVmc5ZGkyRXV0b2V1UXJCRTh3alBCaHdwU2FKMFNXRgpEdVZEcFZ3QlY0K05TdExka0FUT1JWQzR3SGxWMW8vUkZIdENQTXhpdTVPZWJCUWlYS1cvbHlnb0FMMnFtU3FTCkpwMkhQQjRGNmU1NW92RWE2ZjJXdkp1OUQrZ1JhR0tTV0lnaEVFeG50T1lOZXU4eFRHdkhZMDZTRmhxaVk3eTIKZU1rUGdLOGJzaG8xS0ZYbW1MNEZxa1NKS0dyUHF5ampLWHJDaFVNR0RHYWZmYmdFb0FBRgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb2dJQkFBS0NBUUVBdmF4cW9DbDNWNnR5S1daZElnbVEwOXJmMzJvWndtbXBFK3ozekxVdG1kNURKRjlrCjN3eGV1b2RpODZ2YWxRMWUyNnp5RFJQNlZKNlV1SDJpZktlQkNpVFJlcUI5aGdsK1hpZUYyTWR2QWJ1TE1aUjYKTGRSMk0rbFBIYjdjVUpzS20zQk5xSXU1MXB6MnpCclRENmlYQWxid2w3SzRCakFvMVlpMlBkbDF2dWR2cWdQdgpKcHZGZFV2ZmhSMEJqSEpsdmdpS1QzZ2NpemxrNHRFTVRpK0ZuQUVjY3VnUFF0QmduUmJDL29kRFoxYXhIb1o0CjNLeXVQdmRVQjQ1b1FWRUV3WDM0bEhabzFSU3d2VWhFZ05VVk55a0pXY3BQbEFJcmU0Z2hoa0tIVW5UUGdnYS8KYzhCYXN3ZDhBcmlPMUUyelpEQ1RpMG5oeW8ybUdhdnZIM0x3OVFJREFRQUJBb0lCQUJRYngySWJnMCtFR2FKUgorK1d6NWVyUDlaUVdCNDBZN3BmeU00TThZZzFDQnhSQUdNMmMzaDRnWkZrNUN2OXFYM2dpcWJiQk8zVGxLeGMwCkdwbmttRVdmQ2FaYWhYUkVaV1ZPQTE2c0poU2s4V2pjT09mSzhvMG1Xd0RvVHlzc2hMOWQ5SjI5MG9IeU9pZ0IKWUFiMDlLMkcwaE1ERzRkc2E2Zlh5cHBjQjZPcGJzRFFiUUZMeVBYT0duYVl3MG5WN3E0eDM3U1FYRmxIbnVUOApSWWZMZVpjcER2ZkNIYUNTWVlxdnBkVHBEd0FQd2JjY0s3aGNIT3NXL0R2L2lpRHp0ck8wWFczaWhZNUc1SnVDClFMZkYxNmo0M08xeG9iZGI5Skk0aHZsMFV6QzduMTNWUXdsVXRCNDN4ajJRTzFwNWMySXd0R24vQjlOeDZXdUMKSkthN2RBRUNnWUVBOE5PN3F6WGltbm9HUk5tZmc5bGxsUTRYWmVkcktUTnNiWDRoTVJuS0VTQTB0N3l6MXlncQpkdXY2VnF6c3FXd00vVkJRbGxqWDM3NnRETFRVMHNDeXlzZVJFNVg4WkpJMkFtNk5ra3BZTExCVGR4ZnV6VHdxClF5d0IxSmFQbVpxaWk4Sy8rUWQ1QVRFNVNFUEV5clRuL0xMVGZIbUxtSDZ4UHpwbCsxYUdZYlVDZ1lFQXlaK2kKWlM5VXQvZFR2aW10TEQvbW4rWk9FYjhtYWV5Q1BPOUJZQ08wakIxZ2xHN1U5ZFRLRnpGdmh0T2lhbnZaZXZWWQpIc1lvbm53RkNOOEtIMjYzbHJNM2t4MXRxRVF1QTBIeS9MWjNuNTMwS0E3cXVHVXhoSFF1a0tpS09sRWtEcUwwCnpLb3dLRkphV0JtQUNlR2RnSjROdEJQVHZKcWxQK2xQckd1ZzJrRUNnWUF2eHpIeVU2eHpUVVkxSHAvQS9yNWkKaGZzcVluRW1LV2VYaVhCNFYwOTVlbFE3SjVyZVVyK3AvRU1jTXc1NHhsRUZhSXUwYUVmYndlNS9HTmtvUHNhNQo2RUhtQ3RtWjhrLzR4NG9hdmRra2RJNzZqNnIyMkxyaHZMZFlQODZaZ001Q3dBNXFENHQ0S3hYY09tV3VlWm1VCnpyMmFjbHE1bEZrQjNFb2pSUlZBQ1FLQmdIQk5DTy9oQUFnRHExSTA5bTY2SE9PZExJaTM5bFp6VkV0S1hCaUgKYXEzTVF4b0o3WFlMa3BCK2lZY0lZK041bmpYZFo3cWtWc1dIZ0dwamlNamZLMFMyQjlOYVJkUytQUDYxZ2ZqKwpUUHpMeHMxMUdZbWhXNFpTREFtb3htMGErc0ZvUkgrbW4zSW1CSW9qa2V4dkRRSXhocUp4bExMdFUvT1lLVGQ1Ckx6dkJBb0dBUlU2dlBxVHFxekptVXJVREdQRVQ5ZHdUL0Ivdk5qWW9VbjhCdDBmR3VSajJYd0h0TFNVUGNOaE4KRFVydktqQXRqeE1qRFVvZFkxNncycjNzenNFcVlkQmE1bVFsTmhBaEJDbWJQNy9RUXcwMEpYUHZmL2hOcVEzNQp4OWNTdjNNWW9pVG5ZOEQ3TjliZytpSVZlZERYUUFTTGZoUTJHVXpjMEFTQkI5WllDZGc9Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
---
apiVersion: v1
kind: Service
metadata:
  name: argoproj-metrics-poc
  namespace: default
  labels:
    api: argoproj-metrics-poc
    apiserver: "true"
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    api: argoproj-metrics-poc
    apiserver: "true"
